{% set name = "nbval" %}
{% set version = "0.7" %}
{% set sha256 = "1f009c45ce38abda6b3c1b755cf080f7cd25526721fe3f0060fce89f2a9fb861" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pytest
    - six
    - nbformat
    - ipykernel
    - jupyter_client

test:
  imports:
    - nbval

about:
  home: https://github.com/computationalmodelling/nbval
  license: BSD-3-Clause
  license_family: BSD
  license_file: 'LICENSE'
  summary: 'A py.test plugin to validate Jupyter notebooks'

extra:
  recipe-maintainers:
    - kain88-de
    - takluyver
