travis:
  secure:
    BINSTAR_TOKEN: eKW+3PCXrJOqSDWSJeBnAewED+P8cezXoKNj5aFwyCU4p952ultdmpTnB9pVsO+1JBDLXZY2+eChjHq4GwkKQMadQ2iWQ/bCDGWZtRIBkcY9BokjogapuytdpSgzjTpJh0eXcdYE9P3+ZaTPQbVI1UMcs+lOYnmMuLLBA+uipEaST5JBJC11F2R9XsE3iG2bb3622v3/EEgZe3PlFTRUEiTC9PU+HKKq+u89pqvzGZTYDztGg/Seu2YQ+qJDiSc65YTTrbTPHrc4lHRbFC8O7PVxmZYBCQ0rnMRu9rN4GWiH3eN69qx1FPVG59LmOi70OnE6C0NOr3Yh8lnnXZDy3Ac49LJkRc0vHINe1FdhCYsml40dnsTJmT2OJByEr8aH/PdbydNsrAdSVtVHf+oVoudcpGdJgBfI95R0RKbWwRsxEZ/0myNMaEcXeKKcrOkQ4leHYVw5l5qamPajL00ClBhZmkfq1aedCwX1BOKWFCKfOitOEoPOxGlltEzgARpvDe3NU5TTnl1lUtG4cm9fxC5ard7fnTtw8CodDvnyCnypRE44pGF4xzirRLk6F4V54aTPfhg7nofFOOAcHKq98Q9n8Ysizh0zYUqkySq/fx74GhGOT5hu6hqu2FblwHpMCOdMAs7nmOq5fn8P6zcusAo+RoYncg9YAlnz4Iy7jZU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
