travis:
  secure:
    BINSTAR_TOKEN: F4STViLd0BqDU7dTMGOVUuAnGdhDKwWU1dpR3ZjsybPNYJeFGHLlYyE0JHYxAumuhn8z+uE7C8lsoUZ5ph99/k+ZoBZXB65TLAAQQnR9cqgaexprUUlb8ea9j9X/yC9P6wjIcUNxpRaR2lC3+4CedLOWT0ezvbSYXjQz3IrF6qyOAUMszubZveMkEEjvD9eDak5ymGkrJqQGOh/66+YCezJvg0UNKwL5zsPM4hUXTWUrr7fyGPdSgmVY/+bEmw3ldnLA+4yY51HKnM9O72VFgexRf8xji2sHOFVjK17ORCnjCWSuhBJvnkc+EvV2R7cxM1zt2we4Fuxiid/Bp2zwp1/kkcTb0MX6dvPC4DvfdRbu6CAU5OH0ccyHQ2mwMYxiDb4iTn5FfyvDAAFgDLRgmp77D4WG0BlmkHBTuuj4vi277GuIKMyzJs0lJ/V2yaQkGaZGoIOiZLe9kB5rcbH3gFeD848YVWCtibVYsd90QI3pUZFk3jnt3vTVQWgK3WbEIGXS84WpoMYAk51SpgwVZYxAlEYoeNo+s+mawxgJwEPCyUOIKHx5aUHvv/SYRXbr8q04TqNY80/u3HQC0lU27QlMyqTc1jKKSljkC4wtkPysh87GektW1osEpOlosvCgsz/7SstMaRwCTPBDvk6pQlAeYSahYQGEqxtndI0l21A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
