travis:
  secure:
    BINSTAR_TOKEN: N6yKqk/KghDh2bCfiCqOxx0uOwEYSqz2a1AwO+OkXBcMvwT2avpckkmecrg+WaKk5EaPCRlchlMMqvJHjNFBiKa9mEnT06ax8CARudwGtgH8mZamQc80+ndcxino1N3YXPnb5FgxlBPXiRSnDBkuVzRmo7bDzyLsO+aTkXE10ubHsiqC7cneT4ZZ4QcXicLMorLKboFjF8QkcAuKobgmCiYmfcUQ0eIi80A/fEBX32/owyoITE9nZ+2eM/LZJQvPrrrBXd2Ig0ud6Erfge45WF2vhLDdYlv718FGkpuVKFnWkDASETXREIU6I4Gp20KiU8Xk1T/VByK1mVIFs4eZIw4t4S5PqTTDfVl3SPfOST8Gmn7led0W8V8ujbDuZAuU80Vtt0yHSYeiKWzY+vKhLWTSWvBMYAtl5S5LiwvWVFU55ctsFf0mY3ELPTdhanTwOWVYSNNs4354Cc+2eqlbfb78VPZID+KYfR6IUhVc5gjlkGSJWuY1Wsb5NYPg5csBd1K7Hj5ERdmj8S11DCmRZckFVwbMOCMyhH5lv1jxclc7/Me98h+MTL3Imu8aLkQ0mMw0VaoXj/gR01VWxeu6ttBJWtJ0Mk2+qy6EjxK0RahTpn0hTj6clUgWFnRT88QfgKQ+Tntru/s8qdOmHz1y61dbTtVvBMzqK5K477udk8Y=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
